package com.makerlabperu.hangdroid;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

public class GameActivity extends AppCompatActivity {

    String mWord;
    int mFailCounter = 0;
    int mGuessedLetter = 0;
    int mPoints = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_game);
        setRandomWord();
    }


    /**
     * Retrieve the letter inserted and the editText
     * @param v (Button Click)
     */
    public void introduceLetter(View v){
        EditText myEditText = (EditText) findViewById(R.id.editTextLetter);
        String letter = myEditText.getText().toString();

        myEditText.setText("");

        Log.d("MYLOG", "The letter is "+ letter);

        if (letter.length() == 1) {
            checkLetter(letter.toUpperCase());
        } else {
                Toast.makeText(this, "Please Introduce Letter", Toast.LENGTH_SHORT).show();
            }
    }


    /**
     *  Checking if the letter introduced matches any letter in the word to guess
     * @param introduceLetter, letter introduced by user
     */
    public void checkLetter(String introduceLetter){

        boolean letterGuessed = false;
        char charIntroduced = introduceLetter.charAt(0);

        for (int i=0; i < mWord.length() ; i++){
            char charFromTheWord = mWord.charAt(i);

            if (charFromTheWord == introduceLetter.charAt(0)){

                Log.d ("MyLog", "There was one match");

                letterGuessed = true;
                showLettersAtIndex(i, charIntroduced);

                mGuessedLetter++;
            }
        } if (!letterGuessed){
            letterFailed(Character.toString(charIntroduced));
        } if(mGuessedLetter == mWord.length()){
            mPoints++;
            clearScreen();
            setRandomWord();
        }
    }


    public void setRandomWord(){
        String words = "AAHS AALS ABAC ABAS ABBA ABBE ABBS ABED ABET ABID ABLE ABLY ABOS\n" +
                "ABRI ABUT ABYE ABYS ACAI ACCA ACED ACER ACES ACHE ACHY ACID ACME\n" +
                "ACNE ACRE ACTA ACTS ACYL ADAW ADDS ADDY ADIT ADOS ADRY ADZE AEON\n" +
                "AERO AERY AESC AFAR AFFY AFRO AGAR AGAS AGED AGEE AGEN AGER AGES\n" +
                "AGHA AGIN AGIO AGLU AGLY AGMA AGOG AGON AGUE AHED AHEM AHIS AHOY\n" +
                "AIAS AIDE AIDS AIGA AILS AIMS AINE AINS AIRN AIRS AIRT AIRY AITS\n" +
                "AITU AJAR AJEE AKED AKEE AKES AKIN ALAE ALAN ALAP ALAR ALAS ALAY\n" +
                "ALBA ALBE ALBS ALCO ALEC ALEE ALEF ALES ALEW ALFA ALFS ALGA ALIF\n" +
                "ALIT ALKO ALKY ALLS ALLY ALMA ALME ALMS ALOD ALOE ALOW ALPS ALSO\n" +
                "ALTO ALTS ALUM AMAH AMAS AMBO AMEN AMIA AMID AMIE AMIN AMIR AMIS\n" +
                "AMLA AMMO AMOK AMPS AMUS AMYL ANAL ANAN ANAS ANCE ANDS ANES ANEW\n" +
                "ANGA ANIL ANIS ANKH ANNA ANNO ANNS ANOA ANON ANOW ANSA ANTA ANTE\n" +
                "ANTI ANTS ANUS APAY APED APER APES APEX APOD APOS APPS APSE APSO\n" +
                "APTS AQUA ARAK ARAR ARBA ARBS ARCH ARCO ARCS ARDS AREA ARED AREG\n" +
                "ARES ARET AREW ARFS ARIA ARID ARIL ARIS ARKS ARLE ARMS ARMY ARNA\n" +
                "AROW ARPA ARSE ARSY ARTI ARTS ARTY ARUM ARVO ARYL ASAR ASCI ASEA\n" +
                "ASHY ASKS ASPS ATAP ATES ATMA ATOC ATOK ATOM ATOP ATUA AUFS AUKS\n" +
                "AULA AULD AUNE AUNT AURA AUTO AVAL AVAS AVEL AVER AVES AVID AVOS\n" +
                "AVOW AWAY AWDL AWED AWEE AWES AWLS AWNS AWNY AWOL AWRY AXAL AXED\n" +
                "AXEL AXES AXIL AXIS AXLE AXON AYAH AYES AYIN AYRE AYUS AZAN AZON\n" +
                "AZYM BAAL BAAS BABA BABE BABU BABY BACH BACK BACS BADE BADS BAEL\n" +
                "BAFF BAFT BAGH BAGS BAHT BAIL BAIT BAJU BAKE BALD BALE BALK BALL\n" +
                "BALM BALS BALU BAMS BANC BAND BANE BANG BANI BANK BANS BANT BAPS\n" +
                "BAPU BARB BARD BARE BARF BARK BARM BARN BARP BARS BASE BASH BASK\n" +
                "BASS BAST BATE BATH BATS BATT BAUD BAUK BAUR BAWD BAWL BAWN BAWR\n" +
                "BAYE BAYS BAYT BEAD BEAK BEAM BEAN BEAR BEAT BEAU BECK BEDE BEDS\n" +
                "BEDU BEEF BEEN BEEP BEER BEES BEET BEGO BEGS BEIN BELL BELS BELT\n" +
                "BEMA BEND BENE BENI BENJ BENS BENT BERE BERG BERK BERM BEST BETA\n" +
                "BETE BETH BETS BEVY BEYS BHAT BHEL BHUT BIAS BIBB BIBS BICE BIDE\n" +
                "BIDI BIDS BIEN BIER BIFF BIGA BIGG BIGS BIKE BILE BILK BILL BIMA\n" +
                "BIND BINE BING BINK BINS BINT BIOG BIOS BIRD BIRK BIRL BIRO BIRR\n" +
                "BISE BISH BISK BIST BITE BITO BITS BITT BIZE BLAB BLAD BLAE BLAG\n" +
                "BLAH BLAM BLAT BLAW BLAY BLEB BLED BLEE BLET BLEW BLEY BLIN BLIP\n" +
                "BLOB BLOC BLOG BLOT BLOW BLUB BLUE BLUR BOAB BOAK BOAR BOAS BOAT\n" +
                "BOBA BOBS BOCK BODE BODS BODY BOEP BOET BOFF BOGS BOGY BOHO BOHS\n" +
                "BOIL BOIS BOKE BOKO BOKS BOLA BOLD BOLE BOLL BOLO BOLT BOMA BOMB\n" +
                "BONA BOND BONE BONG BONK BONY BOOB BOOH BOOK BOOL BOOM BOON BOOR\n" +
                "BOOS BOOT BOPS BORA BORD BORE BORK BORM BORN BORS BORT BOSH BOSK\n" +
                "BOSS BOTA BOTH BOTS BOTT BOUK BOUN BOUT BOWL BOWR BOWS BOXY BOYF\n" +
                "BOYG BOYO BOYS BOZO BRAD BRAE BRAG BRAK BRAN BRAS BRAT BRAW BRAY\n" +
                "BRED BREE BREI BREN BRER BREW BREY BRIE BRIG BRIK BRIM BRIN BRIO\n" +
                "BRIS BRIT BROD BROG BROO BROS BROW BRRR BRUS BRUT BRUX BUAT BUBA\n" +
                "BUBO BUBS BUBU BUCK BUDA BUDI BUDO BUDS BUFF BUFO BUGS BUHL BUHR\n" +
                "BUIK BUKE BULB BULK BULL BUMF BUMP BUMS BUNA BUND BUNG BUNK BUNN\n" +
                "BUNS BUNT BUOY BURA BURB BURD BURG BURK BURL BURN BURP BURR BURS\n" +
                "BURY BUSH BUSK BUSS BUST BUSY BUTE BUTS BUTT BUYS BUZZ BYDE BYES\n" +
                "BYKE BYRE BYRL BYTE CAAS CABA CABS CACA CADE CADI CADS CAFE CAFF\n" +
                "CAGE CAGS CAGY CAID CAIN CAKE CAKY CALF CALK CALL CALM CALO CALP\n" +
                "CALX CAMA CAME CAMO CAMP CAMS CANE CANG CANN CANS CANT CANY CAPA\n" +
                "CAPE CAPH CAPI CAPO CAPS CARB CARD CARE CARK CARL CARN CARP CARR\n" +
                "CARS CART CASA CASE CASH CASK CAST CATE CATS CAUF CAUK CAUL CAUM\n" +
                "CAUP CAVA CAVE CAVY CAWK CAWS CAYS CEAS CECA CEDE CEDI CEES CEIL\n" +
                "CELL CELS CELT CENS CENT CEPE CEPS CERE CERO CERT CESS CETE CHAD\n" +
                "CHAI CHAL CHAM CHAO CHAP CHAR CHAS CHAT CHAV CHAW CHAY CHEF CHER\n" +
                "CHEW CHEZ CHIA CHIB CHIC CHID CHIK CHIN CHIP CHIS CHIT CHIV CHIZ\n" +
                "CHOC CHOG CHON CHOP CHOU CHOW CHUB CHUG CHUM CHUT CIAO CIDE CIDS\n" +
                "CIEL CIGS CILL CINE CION CIRE CIRL CIST CITE CITO CITS CITY CIVE\n" +
                "CLAD CLAG CLAM CLAN CLAP CLAT CLAW CLAY CLEF CLEG CLEM CLEW CLIP\n" +
                "CLOD CLOG CLON CLOP CLOT CLOU CLOW CLOY CLUB CLUE COAL COAT COAX\n" +
                "COBB COBS COCA COCH COCK COCO CODA CODE CODS COED COFF COFT COGS\n" +
                "COHO COIF COIL COIN COIR COIT COKE COKY COLA COLD COLE COLL COLS\n" +
                "COLT COLY COMA COMB COME COMM COMP COMS COND CONE CONF CONI CONK\n" +
                "CONN CONS CONY COOF COOK COOL COOM COON COOP COOS COOT COPE COPS\n" +
                "COPY CORD CORE CORF CORK CORM CORN CORS CORY COSE COSH COSS COST\n" +
                "COSY COTE COTH COTS COTT COUP COUR COVE COWK COWL COWP COWS COWY\n" +
                "COXA COXY COYS COZE COZY CRAB CRAG CRAM CRAN CRAP CRAW CRAY CRED\n" +
                "CREE CREM CREW CRIB CRIM CRIS CRIT CROC CROG CROP CROW CRUD CRUE\n" +
                "CRUS CRUX CUBE CUBS CUDS CUED CUES CUFF CUIF CUIT CUKE CULL CULM\n" +
                "CULT CUNT CUPS CURB CURD CURE CURF CURL CURN CURR CURS CURT CUSH\n" +
                "CUSK CUSP CUSS CUTE CUTS CWMS CYAN CYMA CYME CYST CYTE CZAR DABS\n" +
                "DACE DACK DADA DADO DADS DAES DAFF DAFT DAGO DAGS DAHL DAHS DAIS\n" +
                "DAKS DALE DALI DALS DALT DAME DAMN DAMP DAMS DANG DANK DANS DANT\n" +
                "DAPS DARB DARE DARG DARI DARK DARN DART DASH DATA DATE DATO DAUB\n" +
                "DAUD DAUR DAUT DAVY DAWD DAWK DAWN DAWS DAWT DAYS DAZE DEAD DEAF\n" +
                "DEAL DEAN DEAR DEAW DEBE DEBS DEBT DECK DECO DEED DEEK DEEM DEEN\n" +
                "DEEP DEER DEES DEET DEEV DEFI DEFT DEFY DEGS DEID DEIF DEIL DEKE\n" +
                "DELE DELF DELI DELL DELO DELS DELT DEME DEMO DEMY DENE DENI DENS\n" +
                "DENT DENY DERE DERM DERN DERO DERV DESI DESK DEUS DEVA DEVS DEWS\n" +
                "DEWY DEXY DEYS DHAK DHAL DHOL DHOW DIAL DIBS DICE DICH DICK DICT\n" +
                "DIDO DIDY DIEB DIED DIEL DIES DIET DIFF DIFS DIGS DIKA DIKE DILL\n" +
                "DIME DIMP DIMS DINE DING DINK DINO DINS DINT DIOL DIPS DIPT DIRE\n" +
                "DIRK DIRL DIRT DISA DISC DISH DISK DISS DITA DITE DITS DITT DITZ\n" +
                "DIVA DIVE DIVI DIVS DIXI DIXY DJIN DOAB DOAT DOBS DOBY DOCK DOCO\n" +
                "DOCS DODO DODS DOEK DOEN DOER DOES DOFF DOGE DOGS DOGY DOHS DOIT\n" +
                "DOJO DOLE DOLL DOLS DOLT DOME DOMS DOMY DONA DONE DONG DONS DOOB\n" +
                "DOOK DOOL DOOM DOON DOOR DOOS DOPA DOPE DOPS DOPY DORB DORE DORK\n" +
                "DORM DORP DORR DORS DORT DORY DOSE DOSH DOSS DOST DOTE DOTH DOTS\n" +
                "DOTY DOUC DOUK DOUM DOUN DOUP DOUR DOUT DOUX DOVE DOWD DOWF DOWL\n" +
                "DOWN DOWP DOWS DOWT DOXY DOYS DOZE DOZY DRAB DRAC DRAD DRAG DRAM\n" +
                "DRAP DRAT DRAW DRAY DREE DREG DREK DREW DREY DRIB DRIP DROP DROW\n" +
                "DRUB DRUG DRUM DRYS DSOS DUAD DUAL DUAN DUAR DUBS DUCE DUCI DUCK\n" +
                "DUCT DUDE DUDS DUED DUEL DUES DUET DUFF DUGS DUIT DUKA DUKE DULE\n" +
                "DULL DULY DUMA DUMB DUMP DUNE DUNG DUNK DUNS DUNT DUOS DUPE DUPS\n" +
                "DURA DURE DURN DURO DURR DUSH DUSK DUST DUTY DWAM DYAD DYED DYER\n" +
                "DYES DYKE DYNE DZHO DZOS EACH EALE EANS EARD EARL EARN EARS EASE\n" +
                "EAST EASY EATH EATS EAUS EAUX EAVE EBBS EBON ECAD ECCE ECCO ECHE\n" +
                "ECHO ECHT ECOD ECOS ECRU ECUS EDDO EDDY EDGE EDGY EDHS EDIT EECH\n" +
                "EELS EELY EERY EEVN EFFS EFTS EGAD EGAL EGER EGGS EGGY EGIS EGMA\n" +
                "EGOS EHED EIDE EIKS EILD EINA EINE EISH EKED EKES EKKA ELAN ELDS\n" +
                "ELFS ELHI ELKS ELLS ELMS ELMY ELSE ELTS EMES EMEU EMIC EMIR EMIT\n" +
                "EMMA EMMY EMOS EMPT EMUS EMYD EMYS ENDS ENES ENEW ENGS ENOL ENOW\n" +
                "ENUF ENVY EOAN EONS EORL EPEE EPHA EPIC EPOS ERAS ERED ERES EREV\n" +
                "ERGO ERGS ERIC ERKS ERNE ERNS EROS ERRS ERST ERUV ESES ESKY ESNE\n" +
                "ESPY ESSE ESTS ETAS ETAT ETCH ETEN ETHE ETHS ETIC ETNA ETUI EUGE\n" +
                "EUGH EUKS EUOI EURO EVEN EVER EVES EVET EVIL EVOE EVOS EWER EWES\n" +
                "EWKS EWTS EXAM EXEC EXED EXES EXIT EXON EXPO EXUL EYAS EYED EYEN\n" +
                "EYER EYES EYNE EYOT EYRA EYRE EYRY FAAN FAAS FABS FACE FACT FADE\n" +
                "FADO FADS FADY FAFF FAGS FAHS FAIK FAIL FAIN FAIR FAIX FAKE FALL\n" +
                "FALX FAME FAND FANE FANG FANK FANO FANS FARD FARE FARL FARM FARO\n" +
                "FARS FART FASH FAST FATE FATS FAUN FAUR FAUT FAUX FAVA FAVE FAWN\n" +
                "FAWS FAYS FAZE FEAL FEAR FEAT FECK FEDS FEEB FEED FEEL FEEN FEER\n" +
                "FEES FEET FEGS FEHM FEHS FEIS FELL FELT FEME FEMS FEND FENI FENS\n" +
                "FENT FEOD FERE FERM FERN FESS FEST FETA FETE FETS FETT FEUD FEUS\n" +
                "FEYS FIAR FIAT FIBS FICE FICO FIDO FIDS FIEF FIER FIFE FIFI FIGO\n" +
                "FIGS FIKE FIKY FILA FILE FILL FILM FILO FILS FIND FINE FINI FINK\n" +
                "FINO FINS FIRE FIRK FIRM FIRN FIRS FISC FISH FISK FIST FITS FITT\n" +
                "FIVE FIXT FIZZ FLAB FLAG FLAK FLAM FLAN FLAP FLAT FLAW FLAX FLAY\n" +
                "FLEA FLED FLEE FLEG FLEW FLEX FLEY FLIC FLIM FLIP FLIR FLIT FLIX\n" +
                "FLOC FLOE FLOG FLOP FLOR FLOW FLUB FLUE FLUS FLUX FOAL FOAM FOBS\n" +
                "FOCI FOEN FOES FOGS FOGY FOHN FOHS FOID FOIL FOIN FOLD FOLK FOND\n" +
                "FONE FONS FONT FOOD FOOL FOOT FOPS FORA FORB FORD FORE FORK FORM\n" +
                "FORT FOSS FOUD FOUL FOUR FOUS FOWL FOXY FOYS FOZY FRAB FRAE FRAG\n" +
                "FRAP FRAS FRAT FRAU FRAY FREE FRET FRIB FRIG FRIS FRIT FRIZ FROE\n" +
                "FROG FROM FROS FROW FRUG FUBS FUCI FUCK FUDS FUEL FUFF FUGS FUGU\n" +
                "FUJI FULL FUME FUMS FUMY FUND FUNG FUNK FUNS FURL FURR FURS FURY\n" +
                "FUSC FUSE FUSS FUST FUTZ FUZE FUZZ FYCE FYKE FYLE FYRD GABS GABY\n" +
                "GADE GADI GADS GAED GAEN GAES GAFF GAGA GAGE GAGS GAID GAIN GAIR\n" +
                "GAIT GAJO GALA GALE GALL GALS GAMA GAMB GAME GAMP GAMS GAMY GANE\n" +
                "GANG GANS GANT GAOL GAPE GAPO GAPS GAPY GARB GARE GARI GARS GART\n" +
                "GASH GASP GAST GATE GATH GATS GAUD GAUM GAUN GAUP GAUR GAUS GAVE\n" +
                "GAWD GAWK GAWP GAYS GAZE GAZY GEAL GEAN GEAR GEAT GECK GEDS GEED\n" +
                "GEEK GEEP GEES GEEZ GEIT GELD GELS GELT GEMS GENA GENE GENS GENT\n" +
                "GENU GEOS GERE GERM GERT GEST GETA GETS GEUM GHAT GHEE GHIS GIBE\n" +
                "GIBS GIDS GIED GIEN GIES GIFT GIGA GIGS GILA GILD GILL GILT GIMP\n" +
                "GING GINK GINN GINS GIOS GIPS GIRD GIRL GIRN GIRO GIRR GIRT GISM\n" +
                "GIST GITE GITS GIVE GIZZ GJUS GLAD GLAM GLED GLEE GLEG GLEI GLEN\n" +
                "GLEY GLIA GLIB GLID GLIM GLIT GLOB GLOM GLOP GLOW GLUE GLUG GLUM\n" +
                "GLUT GNAR GNAT GNAW GNOW GNUS GOAD GOAF GOAL GOAS GOAT GOBO GOBS\n" +
                "GOBY GODS GOEL GOER GOES GOEY GOFF GOGO GOLD GOLE GOLF GOLP GONE\n" +
                "GONG GONK GONS GOOD GOOF GOOG GOOK GOOL GOON GOOP GOOR GOOS GORA\n" +
                "GORE GORI GORM GORP GORY GOSH GOSS GOTH GOUK GOUT GOVS GOWD GOWF\n" +
                "GOWK GOWL GOWN GOYS GRAB GRAD GRAM GRAN GRAT GRAV GRAY GREE GREN\n" +
                "GREW GREX GREY GRID GRIG GRIM GRIN GRIP GRIS GRIT GROG GROK GROT\n" +
                "GROW GRUB GRUE GRUM GUAN GUAR GUBS GUCK GUDE GUES GUFF GUGA GUID\n" +
                "GULA GULE GULF GULL GULP GULS GULY GUMP GUMS GUNG GUNK GUNS GUPS\n" +
                "GURL GURN GURS GURU GUSH GUST GUTS GUVS GUYS GYAL GYBE GYMP GYMS\n" +
                "GYNY GYPS GYRE GYRI GYRO GYTE GYVE HAAF HAAR HABU HACK HADE HADJ\n" +
                "HADS HAED HAEM HAEN HAES HAET HAFF HAFT HAGG HAGS HAHA HAHS HAIK\n" +
                "HAIL HAIN HAIR HAJI HAJJ HAKA HAKE HAKU HALE HALF HALL HALM HALO\n" +
                "HALT HAME HAMS HAND HANG HANK HANT HAPS HAPU HARD HARE HARK HARL\n" +
                "HARM HARN HARO HARP HART HASH HASK HASP HAST HATE HATH HATS HAUD\n" +
                "HAUF HAUL HAUT HAVE HAWK HAWM HAWS HAYS HAZE HAZY HEAD HEAL HEAP\n" +
                "HEAR HEAT HEBE HECH HECK HEED HEEL HEFT HEHS HEID HEIL HEIR HELD\n" +
                "HELE HELL HELM HELO HELP HEME HEMP HEMS HEND HENS HENT HEPS HEPT\n" +
                "HERB HERD HERE HERL HERM HERN HERO HERS HERY HESP HEST HETE HETH\n" +
                "HETS HEWN HEWS HEYS HICK HIDE HIED HIES HIGH HIKE HILA HILD HILI\n" +
                "HILL HILT HIMS HIND HING HINS HINT HIOI HIPS HIPT HIRE HISH HISN\n" +
                "HISS HIST HITS HIVE HIYA HIZZ HOAR HOAS HOAX HOBO HOBS HOCK HODS\n" +
                "HOED HOER HOES HOGG HOGH HOGS HOHA HOHS HOIK HOKA HOKE HOKI HOLD\n" +
                "HOLE HOLK HOLM HOLP HOLS HOLT HOLY HOMA HOME HOMO HOMS HOMY HOND\n" +
                "HONE HONG HONK HONS HOOD HOOF HOOK HOON HOOP HOOT HOPE HOPS HORA\n" +
                "HORE HORI HORN HORS HOSE HOSS HOST HOTE HOTS HOUF HOUR HOUT HOVE\n" +
                "HOWE HOWF HOWK HOWL HOWS HOYA HOYS HUBS HUCK HUED HUER HUES HUFF\n" +
                "HUGE HUGS HUGY HUHU HUIA HUIC HUIS HULA HULE HULK HULL HUMA HUMF\n" +
                "HUMP HUMS HUNG HUNH HUNK HUNS HUNT HUPS HURL HURT HUSH HUSK HUSO\n" +
                "HUSS HUTS HWAN HWYL HYED HYEN HYES HYKE HYLA HYLE HYMN HYPE HYPO\n" +
                "HYPS HYTE IAMB IBEX IBIS ICED ICER ICES ICHS ICKY ICON IDEA IDEE\n" +
                "IDEM IDES IDLE IDLY IDOL IDYL IFFY IGAD IGGS IGLU IKAN IKAT IKON\n" +
                "ILEA ILEX ILIA ILKA ILKS ILLS ILLY IMAM IMID IMMY IMPI IMPS INBY\n" +
                "INCH INFO INGO INIA INKS INKY INLY INNS INRO INTI INTO IONS IOTA\n" +
                "IRED IRES IRID IRIS IRKS IRON ISBA ISIT ISLE ISMS ISNA ISOS ITAS\n" +
                "ITCH ITEM IURE IWIS IXIA IZAR JAAP JABS JACK JADE JAFA JAGA JAGG\n" +
                "JAGS JAIL JAKE JAKS JAMB JAMS JANE JANN JAPE JAPS JARK JARL JARP\n" +
                "JARS JASP JASS JASY JATO JAUK JAUP JAVA JAWS JAXY JAYS JAZY JAZZ\n" +
                "JEAN JEAT JEDI JEED JEEL JEEP JEER JEES JEEZ JEFE JEFF JEHU JELL\n" +
                "JEON JERK JESS JEST JETE JETS JEUX JEWS JIAO JIBB JIBE JIBS JIFF\n" +
                "JIGS JILL JILT JIMP JINK JINN JINS JINX JIRD JISM JIVE JIVY JIZZ\n" +
                "JOBE JOBS JOCK JOCO JOES JOEY JOGS JOHN JOIN JOKE JOKY JOLE JOLL\n" +
                "JOLS JOLT JOMO JONG JOOK JORS JOSH JOSS JOTA JOTS JOUK JOUR JOWL\n" +
                "JOWS JOYS JUBA JUBE JUCO JUDO JUDS JUDY JUGA JUGS JUJU JUKE JUKU\n" +
                "JUMP JUNK JUPE JURA JURE JURY JUST JUTE JUTS JUVE JYNX KAAL KAAS\n" +
                "KABS KADE KADI KAED KAES KAFS KAGO KAGU KAID KAIE KAIF KAIK KAIL\n" +
                "KAIM KAIN KAIS KAKA KAKI KAKS KALE KALI KAMA KAME KAMI KANA KANE\n" +
                "KANG KANS KANT KAON KAPA KAPH KARA KARK KARN KARO KART KATA KATI\n" +
                "KATS KAVA KAWA KAWS KAYO KAYS KAZI KBAR KEAS KEBS KECK KEDS KEEF\n" +
                "KEEK KEEL KEEN KEEP KEET KEFS KEGS KEIR KEKS KELL KELP KELT KEMB\n" +
                "KEMP KENO KENS KENT KEPI KEPS KEPT KERB KERF KERN KERO KESH KEST\n" +
                "KETA KETE KETO KETS KEWL KEYS KHAF KHAN KHAT KHET KHIS KHOR KHUD\n" +
                "KIBE KICK KIDS KIEF KIER KIFF KIFS KIKE KILD KILL KILN KILO KILP\n" +
                "KILT KINA KIND KINE KING KINK KINO KINS KIPE KIPP KIPS KIRK KIRN\n" +
                "KIRS KISH KISS KIST KITE KITH KITS KIVA KIWI KLAP KLIK KNAG KNAP\n" +
                "KNAR KNEE KNEW KNIT KNOB KNOP KNOT KNOW KNUB KNUR KNUT KOAN KOAP\n" +
                "KOAS KOBO KOBS KOEL KOFF KOHA KOHL KOIS KOJI KOLA KOLO KOND KONK\n" +
                "KONS KOOK KOPH KOPS KORA KORE KORO KORS KORU KOSS KOTO KOWS KRAB\n" +
                "KRIS KSAR KUDO KUDU KUEH KUES KUFI KUIA KUKU KULA KUNA KUNE KURI\n" +
                "KURU KUTA KUTI KUTU KUZU KVAS KYAK KYAR KYAT KYBO KYES KYLE KYND\n" +
                "KYNE KYPE KYTE KYUS LABS LACE LACK LACS LACY LADE LADS LADY LAER\n" +
                "LAGS LAHS LAIC LAID LAIK LAIN LAIR LAKE LAKH LAKY LALL LAMA LAMB\n" +
                "LAME LAMP LAMS LANA LAND LANE LANG LANK LANT LANX LAPS LARD LARE\n" +
                "LARI LARK LARN LARS LASE LASH LASS LAST LATE LATH LATI LATS LATU\n" +
                "LAUD LAUF LAVA LAVE LAVS LAWK LAWN LAWS LAYS LAZE LAZO LAZY LEAD\n" +
                "LEAF LEAK LEAL LEAM LEAN LEAP LEAR LEAS LEAT LECH LEED LEEK LEEP\n" +
                "LEER LEES LEET LEFT LEGS LEHR LEIR LEIS LEKE LEKS LEKU LEME LEND\n" +
                "LENG LENO LENS LENT LEPS LEPT LERE LERP LESS LEST LETS LEUD LEVA\n" +
                "LEVE LEVO LEVY LEWD LEYS LEZZ LIAR LIAS LIBS LICE LICH LICK LIDO\n" +
                "LIDS LIED LIEF LIEN LIER LIES LIEU LIFE LIFT LIGS LIKE LILL LILO\n" +
                "LILT LILY LIMA LIMB LIME LIMN LIMO LIMP LIMY LIND LINE LING LINK\n" +
                "LINN LINO LINS LINT LINY LION LIPA LIPE LIPO LIPS LIRA LIRE LIRI\n" +
                "LIRK LISK LISP LIST LITE LITH LITS LITU LIVE LOAD LOAF LOAM LOAN\n" +
                "LOBE LOBI LOBO LOBS LOCA LOCH LOCI LOCK LOCO LODE LODS LOFT LOGE\n" +
                "LOGO LOGS LOGY LOID LOIN LOIR LOKE LOLL LOMA LOME LONE LONG LOOF\n" +
                "LOOK LOOM LOON LOOP LOOR LOOS LOOT LOPE LOPS LORD LORE LORN LORY\n" +
                "LOSE LOSH LOSS LOST LOTA LOTE LOTH LOTI LOTO LOTS LOUD LOUN LOUP\n" +
                "LOUR LOUS LOUT LOVE LOWE LOWN LOWP LOWS LOWT LOYS LUAU LUBE LUCE\n" +
                "LUCK LUDE LUDO LUDS LUES LUFF LUGE LUGS LUIT LUKE LULL LULU LUMA\n" +
                "LUMP LUMS LUNA LUNE LUNG LUNK LUNT LUNY LURE LURK LURS LUSH LUSK\n" +
                "LUST LUTE LUTZ LUVS LUXE LWEI LYAM LYCH LYES LYME LYMS LYNE LYNX\n" +
                "LYRA LYRE LYSE LYTE MAAR MAAS MABE MACE MACH MACK MACS MADE MADS\n" +
                "MAES MAGE MAGG MAGI MAGS MAID MAIK MAIL MAIM MAIN MAIR MAKE MAKI\n" +
                "MAKO MAKS MALA MALE MALI MALL MALM MALS MALT MAMA MAMS MANA MAND\n" +
                "MANE MANG MANI MANO MANS MANY MAPS MARA MARC MARD MARE MARG MARK\n" +
                "MARL MARM MARS MART MARY MASA MASE MASH MASK MASS MAST MASU MATE\n" +
                "MATH MATS MATT MATY MAUD MAUL MAUN MAUT MAWK MAWN MAWR MAWS MAXI\n" +
                "MAYA MAYO MAYS MAZE MAZY MEAD MEAL MEAN MEAT MECK MEDS MEED MEEK\n" +
                "MEER MEES MEET MEFF MEGA MEGS MEIN MELA MELD MELL MELS MELT MEME\n" +
                "MEMO MEMS MEND MENE MENG MENO MENT MENU MEOU MEOW MERC MERE MERI\n" +
                "MERK MERL MESA MESE MESH MESS META METE METH METS MEUS MEVE MEWL\n" +
                "MEWS MEZE MEZZ MHOS MIBS MICA MICE MICH MICK MICO MICS MIDI MIDS\n" +
                "MIEN MIFF MIGG MIGS MIHA MIHI MIKE MILD MILE MILK MILL MILO MILS\n" +
                "MILT MIME MINA MIND MINE MING MINI MINK MINO MINT MINX MINY MIPS\n" +
                "MIRE MIRI MIRK MIRO MIRS MIRV MIRY MISE MISO MISS MIST MITE MITT\n" +
                "MITY MIXT MIXY MIZZ MNAS MOAI MOAN MOAS MOAT MOBE MOBS MOBY MOCH\n" +
                "MOCK MOCS MODE MODI MODS MOER MOES MOFO MOGS MOHR MOIL MOIT MOJO\n" +
                "MOKE MOKI MOKO MOLA MOLD MOLE MOLL MOLS MOLT MOLY MOME MOMI MOMS\n" +
                "MONA MONG MONK MONO MONS MONY MOOD MOOI MOOK MOOL MOON MOOP MOOR\n" +
                "MOOS MOOT MOPE MOPS MOPY MORA MORE MORN MORS MORT MOSE MOSH MOSK\n" +
                "MOSS MOST MOTE MOTH MOTI MOTS MOTT MOTU MOUE MOUP MOUS MOVE MOWA\n" +
                "MOWN MOWS MOXA MOYA MOYL MOYS MOZE MOZO MOZZ MUCH MUCK MUDS MUFF\n" +
                "MUGG MUGS MUID MUIL MUIR MULE MULL MUMM MUMP MUMS MUMU MUNG MUNI\n" +
                "MUNS MUNT MUON MURA MURE MURK MURL MURR MUSE MUSH MUSK MUSO MUSS\n" +
                "MUST MUTE MUTI MUTS MUTT MUZZ MYAL MYCS MYNA MYTH MYXO MZEE NAAM\n" +
                "NAAN NABE NABK NABS NACH NADA NADS NAFF NAGA NAGS NAIF NAIK NAIL\n" +
                "NAIN NALA NAME NAMS NAMU NANA NANE NANS NAOI NAOS NAPA NAPE NAPS\n" +
                "NARC NARD NARE NARK NARY NATS NAVE NAVY NAYS NAZE NAZI NEAL NEAP\n" +
                "NEAR NEAT NEBS NECK NEDS NEED NEEM NEEP NEFS NEGS NEIF NEKS NEMA\n" +
                "NEMN NENE NEON NEPS NERD NERK NESH NESS NEST NETE NETS NETT NEUK\n" +
                "NEUM NEVE NEVI NEWS NEWT NEXT NIBS NICE NICK NIDE NIDI NIDS NIED\n" +
                "NIEF NIES NIFE NIFF NIGH NILL NILS NIMB NIMS NINE NIPA NIPS NIRL\n" +
                "NISH NISI NITE NITS NIXE NIXY NOAH NOBS NOCK NODE NODI NODS NOEL\n" +
                "NOES NOGG NOGS NOIL NOIR NOLE NOLL NOLO NOMA NOME NOMS NONA NONE\n" +
                "NONG NONI NOOK NOON NOOP NOPE NORI NORK NORM NOSE NOSH NOSY NOTA\n" +
                "NOTE NOTT NOUL NOUN NOUP NOUS NOUT NOVA NOWL NOWN NOWS NOWT NOWY\n" +
                "NOYS NUBS NUDE NUFF NUKE NULL NUMB NUNS NURD NURL NURR NURS NUTS\n" +
                "NYAS NYED NYES OAFS OAKS OAKY OARS OARY OAST OATH OATS OBAS OBES\n" +
                "OBEY OBIA OBIS OBIT OBOE OBOL OBOS OCAS OCCY OCHE OCTA ODAH ODAL\n" +
                "ODAS ODDS ODEA ODES ODIC ODOR ODSO ODYL OFAY OFFS OGAM OGEE OGLE\n" +
                "OGRE OHED OHIA OHMS OHOS OIKS OILS OILY OINK OINT OKAS OKAY OKEH\n" +
                "OKES OKRA OKTA OLDS OLDY OLEA OLEO OLES OLID OLIO OLLA OLMS OLPE\n" +
                "OMBU OMEN OMER OMIT OMOV ONCE ONER ONES ONIE ONLY ONOS ONST ONTO\n" +
                "ONUS ONYX OOFS OOFY OOHS OOMS OONS OONT OOPS OOSE OOSY OOTS OOZE\n" +
                "OOZY OPAH OPAL OPED OPEN OPES OPPO OPTS OPUS ORAD ORAL ORBS ORBY\n" +
                "ORCA ORCS ORDO ORDS ORES ORFE ORFS ORGY ORLE ORRA ORTS ORYX ORZO\n" +
                "OSAR OSES OSSA OTIC OTTO OUCH OUDS OUKS OULD OULK OUMA OUPA OUPH\n" +
                "OUPS OURN OURS OUST OUTS OUZO OVAL OVEL OVEN OVER OVUM OWED OWER\n" +
                "OWES OWLS OWLY OWNS OWRE OWSE OWTS OXEN OXER OXES OXID OXIM OYER\n" +
                "OYES OYEZ PAAL PACA PACE PACK PACO PACS PACT PACY PADI PADS PAGE\n" +
                "PAHS PAID PAIK PAIL PAIN PAIR PAIS PALE PALL PALM PALP PALS PALY\n" +
                "PAMS PAND PANE PANG PANS PANT PAPA PAPE PAPS PARA PARD PARE PARK\n" +
                "PARP PARR PARS PART PASE PASH PASS PAST PATE PATH PATS PATU PATY\n" +
                "PAUA PAUL PAVE PAVS PAWA PAWK PAWL PAWN PAWS PAYS PEAG PEAK PEAL\n" +
                "PEAN PEAR PEAS PEAT PEBA PECH PECK PECS PEDS PEED PEEK PEEL PEEN\n" +
                "PEEP PEER PEES PEGH PEGS PEHS PEIN PEKE PELA PELE PELF PELL PELT\n" +
                "PEND PENE PENI PENK PENS PENT PEON PEPO PEPS PERE PERI PERK PERM\n" +
                "PERN PERP PERT PERV PESO PEST PETS PEWS PFFT PFUI PHAT PHEW PHIS\n" +
                "PHIZ PHOH PHON PHOS PHOT PHUT PIAL PIAN PIAS PICA PICE PICK PICS\n" +
                "PIED PIER PIES PIET PIGS PIKA PIKE PIKI PILA PILE PILI PILL PILY\n" +
                "PIMA PIMP PINA PINE PING PINK PINS PINT PINY PION PIOY PIPA PIPE\n" +
                "PIPI PIPS PIPY PIRL PIRN PIRS PISE PISH PISO PISS PITA PITH PITS\n" +
                "PITY PIUM PIXY PIZE PLAN PLAP PLAT PLAY PLEA PLEB PLED PLEW PLEX\n" +
                "PLIE PLIM PLOD PLOP PLOT PLOW PLOY PLUE PLUG PLUM PLUS POAS POCK\n" +
                "POCO PODS POEM POEP POET POGO POGY POIS POKE POKY POLE POLK POLL\n" +
                "POLO POLS POLT POLY POME POMO POMP POMS POND PONE PONG PONK PONS\n" +
                "PONT PONY POOD POOF POOH POOK POOL POON POOP POOR POOS POOT POPE\n" +
                "POPS PORE PORK PORN PORT PORY POSE POSH POSS POST POSY POTE POTS\n" +
                "POTT POUF POUK POUR POUT POWN POWS POXY POZZ PRAD PRAM PRAO PRAT\n" +
                "PRAU PRAY PREE PREM PREP PREX PREY PREZ PRIG PRIM PROA PROB PROD\n" +
                "PROF PROG PROM PROO PROP PROS PROW PRUH PRYS PSIS PSST PTUI PUBE\n" +
                "PUBS PUCE PUCK PUDS PUDU PUER PUFF PUGH PUGS PUHA PUIR PUJA PUKA\n" +
                "PUKE PUKU PULA PULE PULI PULK PULL PULP PULS PULU PULY PUMA PUMP\n" +
                "PUMY PUNA PUNG PUNK PUNS PUNT PUNY PUPA PUPS PUPU PURE PURI PURL\n" +
                "PURR PURS PUSH PUSS PUTS PUTT PUTZ PUYS PYAS PYAT PYES PYET PYIC\n" +
                "PYIN PYNE PYOT PYRE PYRO QADI QAID QATS QOPH QUAD QUAG QUAI QUAT\n" +
                "QUAY QUEP QUEY QUID QUIM QUIN QUIP QUIT QUIZ QUOD QUOP RABI RACA\n" +
                "RACE RACH RACK RACY RADE RADS RAFF RAFT RAGA RAGE RAGG RAGI RAGS\n" +
                "RAHS RAIA RAID RAIK RAIL RAIN RAIS RAIT RAJA RAKE RAKI RAKU RALE\n" +
                "RAMI RAMP RAMS RANA RAND RANG RANI RANK RANT RAPE RAPS RAPT RARE\n" +
                "RARK RASE RASH RASP RAST RATA RATE RATH RATO RATS RATU RAUN RAVE\n" +
                "RAWN RAWS RAYA RAYS RAZE RAZZ READ REAK REAL REAM REAN REAP REAR\n" +
                "REBS RECK RECS REDD REDE REDO REDS REED REEF REEK REEL REEN REES\n" +
                "REFS REFT REGO REGS REHS REIF REIK REIN REIS REKE RELY REMS REND\n" +
                "RENK RENS RENT RENY REOS REPO REPP REPS RESH REST RETE RETS REVS\n" +
                "REWS RHEA RHOS RHUS RIAL RIAS RIBA RIBS RICE RICH RICK RICY RIDE\n" +
                "RIDS RIEL RIEM RIFE RIFF RIFS RIFT RIGG RIGS RILE RILL RIMA RIME\n" +
                "RIMS RIMU RIMY RIND RINE RING RINK RINS RIOT RIPE RIPP RIPS RIPT\n" +
                "RISE RISK RISP RITE RITS RITT RITZ RIVA RIVE RIVO RIZA ROAD ROAM\n" +
                "ROAN ROAR ROBE ROBS ROCH ROCK ROCS RODE RODS ROED ROES ROIL ROIN\n" +
                "ROJI ROKE ROKS ROKY ROLE ROLF ROLL ROMA ROMP ROMS RONE RONG RONT\n" +
                "ROOD ROOF ROOK ROOM ROON ROOP ROOS ROOT ROPE ROPY RORE RORT RORY\n" +
                "ROSE ROST ROSY ROTA ROTE ROTI ROTL ROTO ROTS ROUE ROUL ROUM ROUP\n" +
                "ROUT ROUX ROVE ROWS ROWT RUBE RUBS RUBY RUCK RUCS RUDD RUDE RUDS\n" +
                "RUED RUER RUES RUFF RUGA RUGS RUIN RUKH RULE RULY RUME RUMP RUMS\n" +
                "RUND RUNE RUNG RUNS RUNT RURP RURU RUSA RUSE RUSH RUSK RUST RUTH\n" +
                "RUTS RYAL RYAS RYES RYFE RYKE RYND RYOT RYPE SABE SABS SACK SACS\n" +
                "SADE SADI SADO SADS SAFE SAFT SAGA SAGE SAGO SAGS SAGY SAIC SAID\n" +
                "SAIL SAIM SAIN SAIR SAIS SAKE SAKI SALE SALL SALP SALS SALT SAMA\n" +
                "SAME SAMP SAMS SAND SANE SANG SANK SANS SANT SAPS SARD SARI SARK\n" +
                "SARS SASH SASS SATE SATI SAUL SAUT SAVE SAVS SAWN SAWS SAXE SAYS\n" +
                "SCAB SCAD SCAG SCAM SCAN SCAR SCAT SCAW SCOG SCOP SCOT SCOW SCRY\n" +
                "SCUD SCUG SCUL SCUM SCUP SCUR SCUT SCYE SEAL SEAM SEAN SEAR SEAS\n" +
                "SEAT SECH SECO SECS SECT SEED SEEK SEEL SEEM SEEN SEEP SEER SEES\n" +
                "SEGO SEGS SEIF SEIK SEIL SEIR SEIS SEKT SELD SELE SELF SELL SELS\n" +
                "SEME SEMI SENA SEND SENE SENS SENT SEPS SEPT SERA SERE SERF SERK\n" +
                "SERR SERS SESE SESH SESS SETA SETS SETT SEWN SEWS SEXT SEXY SEYS\n" +
                "SHAD SHAG SHAH SHAM SHAN SHAT SHAW SHAY SHEA SHED SHES SHET SHEW\n" +
                "SHIM SHIN SHIP SHIR SHIT SHIV SHMO SHOD SHOE SHOG SHOO SHOP SHOT\n" +
                "SHOW SHRI SHUL SHUN SHUT SHWA SIAL SIBB SIBS SICE SICH SICK SICS\n" +
                "SIDA SIDE SIDH SIEN SIES SIFT SIGH SIGN SIJO SIKA SIKE SILD SILE\n" +
                "SILK SILL SILO SILT SIMA SIMI SIMP SIMS SIND SINE SING SINH SINK\n" +
                "SINS SIPE SIPS SIRE SIRI SIRS SISS SIST SITE SITH SITS SITZ SIZE\n" +
                "SIZY SJOE SKAG SKAS SKAT SKAW SKEE SKEG SKEN SKEO SKEP SKER SKET\n" +
                "SKEW SKID SKIM SKIN SKIO SKIP SKIS SKIT SKOL SKRY SKUA SKUG SKYF\n" +
                "SKYR SLAB SLAE SLAG SLAM SLAP SLAT SLAW SLAY SLED SLEE SLEW SLEY\n" +
                "SLID SLIM SLIP SLIT SLOB SLOE SLOG SLOP SLOT SLOW SLUB SLUE SLUG\n" +
                "SLUM SLUR SLUT SMEE SMEW SMIR SMIT SMOG SMUG SMUR SMUT SNAB SNAG\n" +
                "SNAP SNAR SNAW SNEB SNED SNEE SNIB SNIG SNIP SNIT SNOB SNOD SNOG\n" +
                "SNOT SNOW SNUB SNUG SNYE SOAK SOAP SOAR SOBA SOBS SOCA SOCK SOCS\n" +
                "SODA SODS SOFA SOFT SOGS SOHO SOHS SOIL SOJA SOKE SOLA SOLD SOLE\n" +
                "SOLI SOLO SOLS SOMA SOME SOMS SOMY SONE SONG SONS SOOK SOOL SOOM\n" +
                "SOON SOOP SOOT SOPH SOPS SORA SORB SORD SORE SORI SORN SORT SOSS\n" +
                "SOTH SOTS SOUK SOUL SOUM SOUP SOUR SOUS SOUT SOVS SOWF SOWL SOWM\n" +
                "SOWN SOWP SOWS SOYA SOYS SPAE SPAG SPAM SPAN SPAR SPAS SPAT SPAW\n" +
                "SPAY SPAZ SPEC SPED SPEK SPET SPEW SPIC SPIE SPIF SPIK SPIM SPIN\n" +
                "SPIT SPIV SPOD SPOT SPRY SPUD SPUE SPUG SPUN SPUR SRIS STAB STAG\n" +
                "STAP STAR STAT STAW STAY STED STEM STEN STEP STET STEW STEY STIE\n" +
                "STIM STIR STOA STOB STOP STOT STOW STUB STUD STUM STUN STYE SUBA\n" +
                "SUBS SUCH SUCK SUDD SUDS SUED SUER SUES SUET SUGH SUID SUIT SUKH\n" +
                "SUKS SULK SULU SUMO SUMP SUMS SUMY SUNG SUNK SUNN SUNS SUPE SUPS\n" +
                "SUQS SURA SURD SURE SURF SUSS SUSU SWAB SWAD SWAG SWAM SWAN SWAP\n" +
                "SWAT SWAY SWEE SWEY SWIG SWIM SWIZ SWOB SWOP SWOT SWUM SYBO SYCE\n" +
                "SYED SYEN SYES SYKE SYLI SYNC SYND SYNE SYPE SYPH TAAL TABI TABS\n" +
                "TABU TACE TACH TACK TACO TACT TADS TAED TAEL TAES TAGS TAHA TAHR\n" +
                "TAIG TAIL TAIN TAIS TAIT TAKA TAKE TAKI TAKS TAKY TALA TALC TALE\n" +
                "TALI TALK TALL TAME TAMP TAMS TANA TANE TANG TANH TANK TANS TAOS\n" +
                "TAPA TAPE TAPS TAPU TARA TARE TARN TARO TARP TARS TART TASH TASK\n" +
                "TASS TATE TATH TATS TATT TATU TAUS TAUT TAVA TAVS TAWA TAWS TAWT\n" +
                "TAXA TAXI TAYS TEAD TEAK TEAL TEAM TEAR TEAS TEAT TECH TECS TEDS\n" +
                "TEDY TEED TEEK TEEL TEEM TEEN TEER TEES TEFF TEFS TEGG TEGS TEGU\n" +
                "TEHR TEIL TELA TELD TELE TELL TELS TELT TEME TEMP TEMS TEND TENE\n" +
                "TENS TENT TEPA TERF TERM TERN TEST TETE TETH TETS TEWS TEXT THAE\n" +
                "THAN THAR THAT THAW THEE THEM THEN THEW THEY THIG THIN THIO THIR\n" +
                "THIS THON THOU THRO THRU THUD THUG THUS TIAR TICE TICH TICK TICS\n" +
                "TIDE TIDS TIDY TIED TIER TIES TIFF TIFT TIGE TIGS TIKA TIKE TIKI\n" +
                "TILE TILL TILS TILT TIME TIND TINE TING TINK TINS TINT TINY TIPI\n" +
                "TIPS TIPT TIRE TIRL TIRO TIRR TITE TITI TITS TIVY TIZZ TOAD TOBY\n" +
                "TOCK TOCO TOCS TODS TODY TOEA TOED TOES TOEY TOFF TOFT TOFU TOGA\n" +
                "TOGE TOGS TOHO TOIL TOIT TOKE TOKO TOLA TOLD TOLE TOLL TOLT TOLU\n" +
                "TOMB TOME TOMO TOMS TONE TONG TONK TONS TONY TOOK TOOL TOOM TOON\n" +
                "TOOT TOPE TOPH TOPI TOPO TOPS TORA TORC TORE TORI TORN TORO TORR\n" +
                "TORS TORT TORY TOSA TOSE TOSH TOSS TOST TOTE TOTS TOUK TOUN TOUR\n" +
                "TOUT TOWN TOWS TOWT TOWY TOYO TOYS TOZE TRAD TRAM TRAP TRAT TRAY\n" +
                "TREE TREF TREK TRES TRET TREW TREY TREZ TRIE TRIG TRIM TRIN TRIO\n" +
                "TRIP TROD TROG TRON TROP TROT TROW TROY TRUE TRUG TRYE TRYP TSAR\n" +
                "TSKS TUAN TUBA TUBE TUBS TUCK TUFA TUFF TUFT TUGS TUIS TULE TUMP\n" +
                "TUMS TUNA TUND TUNE TUNG TUNS TUNY TUPS TURD TURF TURK TURM TURN\n" +
                "TUSH TUSK TUTS TUTU TUZZ TWAE TWAL TWAS TWAT TWAY TWEE TWIG TWIN\n" +
                "TWIT TWOS TYDE TYED TYEE TYER TYES TYGS TYIN TYKE TYMP TYND TYNE\n" +
                "TYPE TYPO TYPP TYPY TYRE TYRO TYTE TZAR UDAL UDON UDOS UEYS UFOS\n" +
                "UGHS UGLY UKES ULAN ULES ULEX ULNA ULUS ULVA UMBO UMPH UMPS UMPY\n" +
                "UNAI UNAU UNBE UNCE UNCI UNCO UNDE UNDO UNDY UNIS UNIT UNTO UPAS\n" +
                "UPBY UPDO UPGO UPON UPSY UPTA URAO URBS URDE URDS URDY UREA URES\n" +
                "URGE URIC URNS URPS URSA URUS URVA USED USER USES UTAS UTES UTIS\n" +
                "UTUS UVAE UVAS UVEA VACS VADE VAES VAGI VAGS VAIL VAIN VAIR VALE\n" +
                "VALI VAMP VANE VANG VANS VANT VARA VARE VARS VARY VASA VASE VAST\n" +
                "VATS VATU VAUS VAUT VAVS VAWS VEAL VEEP VEER VEES VEGA VEGO VEHM\n" +
                "VEIL VEIN VELA VELD VELE VELL VENA VEND VENT VERA VERB VERD VERS\n" +
                "VERT VERY VEST VETO VETS VEXT VIAE VIAL VIAS VIBE VIBS VICE VIDE\n" +
                "VIDS VIED VIER VIES VIEW VIGA VIGS VILD VILE VILL VIMS VINA VINE\n" +
                "VINO VINS VINT VINY VIOL VIRE VIRL VISA VISE VITA VITE VIVA VIVE\n" +
                "VIVO VIZY VLEI VOAR VOES VOID VOLA VOLE VOLK VOLS VOLT VORS VOTE\n" +
                "VOWS VRIL VROT VROU VROW VUGG VUGH VUGS VULN VUMS WAAC WABS WACK\n" +
                "WADD WADE WADI WADS WADT WADY WAES WAFF WAFT WAGE WAGS WAID WAIF\n" +
                "WAIL WAIN WAIR WAIS WAIT WAKA WAKE WAKF WALD WALE WALI WALK WALL\n" +
                "WALY WAME WAND WANE WANG WANK WANS WANT WANY WAPS WAQF WARB WARD\n" +
                "WARE WARK WARM WARN WARP WARS WART WARY WASE WASH WASM WASP WAST\n" +
                "WATE WATS WATT WAUK WAUL WAUR WAVE WAVY WAWA WAWE WAWL WAWS WAXY\n" +
                "WAYS WEAK WEAL WEAN WEAR WEBS WEDS WEED WEEK WEEL WEEM WEEN WEEP\n" +
                "WEER WEES WEET WEFT WEID WEIL WEIR WEKA WELD WELK WELL WELT WEMB\n" +
                "WEMS WENA WEND WENS WENT WEPT WERE WERO WERT WEST WETA WETS WEXE\n" +
                "WEYS WHAE WHAM WHAP WHAT WHEE WHEN WHET WHEW WHEY WHID WHIG WHIM\n" +
                "WHIN WHIO WHIP WHIR WHIT WHIZ WHOA WHOM WHOP WHOT WHOW WHUP WHYS\n" +
                "WICE WICH WICK WIDE WIEL WIFE WIGS WILD WILE WILI WILL WILT WILY\n" +
                "WIMP WIND WINE WING WINK WINN WINO WINS WINY WIPE WIRE WIRY WISE\n" +
                "WISH WISP WISS WIST WITE WITH WITS WIVE WOAD WOCK WOES WOFS WOGS\n" +
                "WOKE WOKS WOLD WOLF WOMB WONK WONS WONT WOOD WOOF WOOL WOON WOOS\n" +
                "WOOT WOPS WORD WORE WORK WORM WORN WORT WOST WOTS WOVE WOWF WOWS\n" +
                "WRAP WREN WRIT WUDS WUDU WULL WUSS WYCH WYES WYLE WYND WYNN WYNS\n" +
                "WYTE XYST YAAR YABA YACK YADS YAFF YAGI YAGS YAHS YAKS YALD YALE\n" +
                "YAMS YANG YANK YAPP YAPS YARD YARE YARK YARN YARR YATE YAUD YAUP\n" +
                "YAWL YAWN YAWP YAWS YAWY YAYS YBET YEAD YEAH YEAN YEAR YEAS YEBO\n" +
                "YECH YEDE YEED YEGG YELD YELK YELL YELM YELP YELT YENS YEPS YERD\n" +
                "YERK YESK YEST YETI YETT YEUK YEVE YEWS YGOE YIDS YIKE YILL YINS\n" +
                "YIPE YIPS YIRD YIRK YIRR YITE YLEM YLKE YMPE YMPT YOBS YOCK YODE\n" +
                "YODH YODS YOGA YOGH YOGI YOKE YOKS YOLD YOLK YOMP YOND YONI YONT\n" +
                "YOOF YOOP YORE YORK YORP YOUK YOUR YOUS YOWE YOWL YOWS YUAN YUCA\n" +
                "YUCH YUCK YUFT YUGA YUGS YUKE YUKO YUKS YUKY YULE YUMP YUNX YUPS\n" +
                "YURT YUTZ YUZU YWIS ZACK ZAGS ZANY ZAPS ZARF ZATI ZEAL ZEAS ZEBU\n" +
                "ZEDS ZEES ZEIN ZEKS ZELS ZEPS ZERK ZERO ZEST ZETA ZEZE ZHOS ZIFF\n" +
                "ZIGS ZILA ZILL ZIMB ZINC ZINE ZING ZINS ZIPS ZITE ZITI ZITS ZIZZ\n" +
                "ZOBO ZOBU ZOEA ZOIC ZOLS ZONA ZONE ZONK ZOOM ZOON ZOOS ZOOT ZORI\n" +
                "ZOUK ZULU ZUPA ZURF ZYGA ZYME ZZZS";

        String [] arrayWords = words.split(" ");

        Log.d("MYLOG", "The array length is " +arrayWords.length);

        int randomNumber = (int) (Math.random() * arrayWords.length);

        String randomWord = arrayWords[randomNumber];

        mWord = randomWord;
    }


    public void clearScreen(){
        TextView textViewFailed = (TextView) findViewById(R.id.textView6);
        textViewFailed.setText("");

        mGuessedLetter = 0;
        mFailCounter = 0;


        LinearLayout layoutLetters = (LinearLayout) findViewById(R.id.layoutLetters);
        for (int i = 0; i < layoutLetters.getChildCount(); i++){
            TextView currentTextView = (TextView) layoutLetters.getChildAt(i);
            currentTextView.setText("_");
        }

        ImageView imageView = (ImageView) findViewById(R.id.imageView);
        imageView.setImageResource(R.drawable.hangdroid_0);
    }


    public void letterFailed(String letterFailed){

        TextView textViewFailed = (TextView) findViewById(R.id.textView6);

        String previousFail = textViewFailed.getText().toString();
        textViewFailed.setText(previousFail + letterFailed);

        mFailCounter++;
        ImageView imageView = (ImageView) findViewById(R.id.imageView);

        if (mFailCounter == 1) {
            imageView.setImageResource(R.drawable.hangdroid_1);
        }  else if (mFailCounter == 2){
            imageView.setImageResource(R.drawable.hangdroid_2);
        }  else if (mFailCounter == 3){
            imageView.setImageResource(R.drawable.hangdroid_3);
        }  else if (mFailCounter == 4){
            imageView.setImageResource(R.drawable.hangdroid_4);
        }  else if (mFailCounter == 5){
            imageView.setImageResource(R.drawable.hangdroid_5);
        } else if (mFailCounter == 6){
            Intent gameOverIntent = new Intent(this, GameOverActivity.class);

            gameOverIntent.putExtra("POINTS_IDENTIFIER", mPoints);

            startActivity(gameOverIntent);

            finish();
        }
    }


    /**
     *  Displaying a letter guessed by the user
     * @param position of the letter
     * @param letterGuessed
     */
    public void showLettersAtIndex(int position, char letterGuessed){

        LinearLayout layoutletter = (LinearLayout) findViewById(R.id.layoutLetters);

        TextView textView = (TextView) layoutletter.getChildAt(position);

        textView.setText(Character.toString(letterGuessed));

    }
}
